version: "3.8"
services:
  cacttusDb:
    image: postgres:13
    ports:
      - 5435:5432
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: Fleet
      POSTGRES_USER: spines
      POSTGRES_PASSWORD: Cacttus123
      PGDATA: /var/lib/postgresql/data/fleet
    network_mode: bridge


















volumes:
  postgres-data: